repos:
- repo: local
  hooks:
  -   id: run-unit-tests
      name: Run unit tests
      entry: ./.git/hooks/run-unit-tests
      language: script
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
